version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sportlife#32#sqlserver#32#
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - sqlserver
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
