version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sportlife#32#sqlserver#32#
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql # Add volume for persistence

  exercise-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercise-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080" 
    depends_on:
      - sqlserver  # Ensure SQL Server starts before the API
    networks:
      - app-network

  blazorapp:
    build:
      context: ../FitskedApp
      dockerfile: Dockerfile  
    container_name: blazorapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
    depends_on:
      - sqlserver 
      - exercise-api  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
    driver: local
