version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sportlife#32#sqlserver#32#
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_DB_CONNECTION_STRING=Server=sqlserver;Database=exercises-api;User Id=sa;Password=Sportlife#32#sqlserver#32#;Encrypt=False;TrustServerCertificate=True;MultipleActiveResultSets=true
      - AWS_EC2=true
      - EF_MIGRATE=true
    ports:
      - "5000:5000" 
    depends_on:
      - sqlserver
    networks:
      - app-network

  app:
    build:
      context: ../FitskedApp
      dockerfile: Dockerfile  
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=sqlserver;Database=fitsked;User Id=sa;Password=Sportlife#32#sqlserver#32#;Encrypt=False;TrustServerCertificate=True;MultipleActiveResultSets=true
      - API_BASE_URL=http://exercise-api:5000
      - AWS_EC2=true
    ports:
      - "80:8080"
    depends_on:
      - sqlserver 
      - api  
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

volumes:
  sql_data:
    driver: local
