version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sportlife#32#sqlserver#32#
    ports:
      - "1433:1433" # Expose SQL Server to the host
    networks:
      - app-network

  exercise-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercise-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080" # Expose your API to the host
    depends_on:
      - sqlserver # Ensure SQL Server starts before the API
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
