// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exercise_api.ExerciseContext;

#nullable disable

namespace exercise_api.Migrations
{
    [DbContext(typeof(ExerciseDbContext))]
    [Migration("20241119231501_AddingVideoUrlsToMigration")]
    partial class AddingVideoUrlsToMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exercise_api.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ExerciseType = "Core",
                            Name = "Chin Ups",
                            VideoUrl = "https://www.youtube.com/watch?v=mTRT9O5r8Wg",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ExerciseType = "Core",
                            Name = "Backups",
                            VideoUrl = "https://www.youtube.com/watch?v=EAJJQjF2j6s",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ExerciseType = "Core",
                            Name = "Barbell Curls",
                            VideoUrl = "https://www.youtube.com/watch?v=qUX2ckeMa08",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 4,
                            ExerciseType = "Core",
                            Name = "Behind Head Overhead Barbell Press",
                            VideoUrl = "https://www.youtube.com/watch?v=7c2ITqTmv_Y",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 5,
                            ExerciseType = "Core",
                            Name = "Landmine Twist Push",
                            VideoUrl = "https://www.youtube.com/watch?v=sQ6xBgPRdPU",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 6,
                            ExerciseType = "Core",
                            Name = "Landmine Pull Rotation",
                            VideoUrl = "https://www.youtube.com/watch?v=80GP0VlFXsM",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 7,
                            ExerciseType = "Core",
                            Name = "Landmine Rotations",
                            VideoUrl = "https://www.youtube.com/watch?v=MswsBPLGhE8",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 8,
                            ExerciseType = "Core",
                            Name = "Overhead Squats",
                            VideoUrl = "https://www.youtube.com/watch?v=6wzpijkqZzg",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 9,
                            ExerciseType = "Core",
                            Name = "Front Lunges",
                            VideoUrl = "https://www.youtube.com/watch?v=g8-Ge9S0aUw",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 10,
                            ExerciseType = "Core",
                            Name = "Side Lunges",
                            VideoUrl = "https://www.youtube.com/watch?v=1D_tsUSW3ZY",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 11,
                            ExerciseType = "Accessory",
                            Name = "Hip Ups",
                            VideoUrl = "https://www.youtube.com/watch?v=Ku2P2ON7rYw",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 12,
                            ExerciseType = "Secondary",
                            Name = "Calf Raises",
                            VideoUrl = "https://www.youtube.com/watch?v=c5Kv6-fnTj8",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 13,
                            ExerciseType = "Accessory",
                            Name = "Sidekicks",
                            VideoUrl = "https://www.youtube.com/watch?v=IV1V8G_5fVU",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 14,
                            ExerciseType = "Accessory",
                            Name = "Banded Overhead Rotations",
                            VideoUrl = "https://www.youtube.com/watch?v=8ye8EARmRQQ",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 15,
                            ExerciseType = "Accessory",
                            Name = "Reverse Grip Banded Overhead Rotations",
                            VideoUrl = "https://www.youtube.com/watch?v=8ye8EARmRQQ",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 16,
                            ExerciseType = "Accessory",
                            Name = "Front Palm Down Banded Pulls",
                            VideoUrl = "https://www.youtube.com/watch?v=MnDpmNYUjbc",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 17,
                            ExerciseType = "Accessory",
                            Name = "Banded Palm Up Banded Pulls",
                            VideoUrl = "https://www.youtube.com/watch?v=MnDpmNYUjbc",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 18,
                            ExerciseType = "Accessory",
                            Name = "Back Banded Palm Down Pulls",
                            VideoUrl = "https://www.youtube.com/watch?v=yVcEkvgymt8",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 19,
                            ExerciseType = "Accessory",
                            Name = "Back Banded Palm Up Pulls",
                            VideoUrl = "https://www.youtube.com/watch?v=yVcEkvgymt8",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 20,
                            ExerciseType = "Accessory",
                            Name = "Swimmers",
                            VideoUrl = "https://www.youtube.com/watch?v=M8a1cgnhyqk",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 21,
                            ExerciseType = "Core",
                            Name = "Bench Press",
                            VideoUrl = "https://www.youtube.com/watch?v=wzq57DB5Ppg",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 22,
                            ExerciseType = "Core",
                            Name = "Overhead Press",
                            VideoUrl = "https://www.youtube.com/watch?v=-5MmFTKLC-0",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 23,
                            ExerciseType = "Core",
                            Name = "Pull-Ups",
                            VideoUrl = "https://www.youtube.com/watch?v=aAggnpPyR6E",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 24,
                            ExerciseType = "Secondary",
                            Name = "Dumbbell Rows",
                            VideoUrl = "https://www.youtube.com/watch?v=3mmaTrhUWNM",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 25,
                            ExerciseType = "Secondary",
                            Name = "Incline Bench Press",
                            VideoUrl = "https://www.youtube.com/watch?v=2jFFCy8JBU8",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 26,
                            ExerciseType = "Secondary",
                            Name = "Dips",
                            VideoUrl = "https://www.youtube.com/watch?v=CRP7tS7RIJU",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 27,
                            ExerciseType = "Accessory",
                            Name = "Lateral Raises",
                            VideoUrl = "https://www.youtube.com/watch?v=c3FkUjXxWmM",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 28,
                            ExerciseType = "Accessory",
                            Name = "Tricep Pushdowns",
                            VideoUrl = "https://www.youtube.com/watch?v=5oMnUzy_hQ8",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 30,
                            ExerciseType = "Core",
                            Name = "Squat",
                            VideoUrl = "https://www.youtube.com/watch?v=ultWZbUMPL8",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 31,
                            ExerciseType = "Core",
                            Name = "Deadlift",
                            VideoUrl = "https://www.youtube.com/watch?v=op9kVnSso6Q",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 33,
                            ExerciseType = "Secondary",
                            Name = "Bulgarian Split Squat",
                            VideoUrl = "https://www.youtube.com/watch?v=9p5e2BSvoLs",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 34,
                            ExerciseType = "Secondary",
                            Name = "Romanian Deadlift",
                            VideoUrl = "https://www.youtube.com/watch?v=GZAKFRNtxLY",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 35,
                            ExerciseType = "Secondary",
                            Name = "Step-Ups",
                            VideoUrl = "https://www.youtube.com/watch?v=i1uM-CbfTBo",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 37,
                            ExerciseType = "Accessory",
                            Name = "Glute Bridges",
                            VideoUrl = "https://www.youtube.com/watch?v=m0AIU1dCVkU",
                            WorkoutType = "LowerBodyStrength"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
