// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exercise_api.ExerciseContext;

#nullable disable

namespace exercise_api.Migrations
{
    [DbContext(typeof(ExerciseDbContext))]
    [Migration("20241121192248_NewMigrationTestingLocalSeedData")]
    partial class NewMigrationTestingLocalSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exercise_api.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ExerciseType = "Core",
                            Name = "Chin Ups",
                            VideoUrl = "https://www.youtube.com/results?search_query=chin+ups+demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ExerciseType = "Core",
                            Name = "Behind Neck Pull Ups",
                            VideoUrl = "https://www.youtube.com/results?search_query=Behind+The+Neck+Pull+Up",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ExerciseType = "Core",
                            Name = "Barbell Curls",
                            VideoUrl = "https://www.youtube.com/results?search_query=Barbell+Biceps+Curl+-+Demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 4,
                            ExerciseType = "Core",
                            Name = "Behind Head Overhead Barbell Press",
                            VideoUrl = "https://www.youtube.com/results?search_query=Behind+the+Neck+Overhead+Press+demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 5,
                            ExerciseType = "Core",
                            Name = "Landmine Twist Push",
                            VideoUrl = "https://www.youtube.com/results?search_query=Landmine+twist+press",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 6,
                            ExerciseType = "Core",
                            Name = "Landmine Pull Rotation",
                            VideoUrl = "https://www.youtube.com/results?search_query=Power%3A+Landmine+Pull+to+Press",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 7,
                            ExerciseType = "Core",
                            Name = "Landmine Rotations",
                            VideoUrl = "https://www.youtube.com/results?search_query=Landmine+Rotation",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 8,
                            ExerciseType = "Core",
                            Name = "Overhead Squats",
                            VideoUrl = "https://www.youtube.com/results?search_query=OVERHEAD+SQUAT",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 9,
                            ExerciseType = "Core",
                            Name = "Front Lunges",
                            VideoUrl = "https://www.youtube.com/results?search_query=How+To+Do+A+Forward+Lunge",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 10,
                            ExerciseType = "Core",
                            Name = "Side Lunges",
                            VideoUrl = "https://www.youtube.com/results?search_query=Side+Lunges+Demonstration",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 11,
                            ExerciseType = "Accessory",
                            Name = "Hip Flexor Raises",
                            VideoUrl = "https://www.youtube.com/results?search_query=Kettlebell+Hip+Flexor+Raise",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 12,
                            ExerciseType = "Secondary",
                            Name = "Calf Raises",
                            VideoUrl = "https://www.youtube.com/results?search_query=Calf+Raise+Exercise+Demo",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 13,
                            ExerciseType = "Accessory",
                            Name = "Sidekicks",
                            VideoUrl = "https://www.youtube.com/results?search_query=Alternating+Side+Kicks",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 14,
                            ExerciseType = "Accessory",
                            Name = "Banded Overhead Rotations",
                            VideoUrl = "https://www.youtube.com/results?search_query=Resistance+Band+Overhead+Rotation",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 15,
                            ExerciseType = "Accessory",
                            Name = "Reverse Grip Banded Overhead Rotations",
                            VideoUrl = "https://www.youtube.com/results?search_query=Resistance+Band+Overhead+Rotation",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 16,
                            ExerciseType = "Accessory",
                            Name = "Front Palm Down Banded Pulls",
                            VideoUrl = "https://www.youtube.com/results?search_query=Band+Pull+Apart",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 17,
                            ExerciseType = "Accessory",
                            Name = "Banded Palm Up Banded Pulls",
                            VideoUrl = "https://www.youtube.com/results?search_query=Band+Pull+Apart",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 18,
                            ExerciseType = "Accessory",
                            Name = "Banded Chest Flys",
                            VideoUrl = "https://www.youtube.com/results?search_query=Band+Chest+Fly",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 20,
                            ExerciseType = "Accessory",
                            Name = "Prone Swimmers",
                            VideoUrl = "https://www.youtube.com/results?search_query=Prone+Swimmers",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 21,
                            ExerciseType = "Core",
                            Name = "Bench Press",
                            VideoUrl = "https://www.youtube.com/results?search_query=bench+press",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 22,
                            ExerciseType = "Core",
                            Name = "Overhead Press",
                            VideoUrl = "https://www.youtube.com/results?search_query=How+To+Perfect+The+Overhead+Press",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 23,
                            ExerciseType = "Core",
                            Name = "Pull-Ups",
                            VideoUrl = "https://www.youtube.com/results?search_query=pull+up+demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 24,
                            ExerciseType = "Secondary",
                            Name = "Dumbbell Rows",
                            VideoUrl = "https://www.youtube.com/results?search_query=Dumbbell+Row+(Exercise+Demo)",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 25,
                            ExerciseType = "Secondary",
                            Name = "Incline Bench Press",
                            VideoUrl = "https://www.youtube.com/results?search_query=How+To+Do+A+Barbell+Incline+Bench+Press",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 26,
                            ExerciseType = "Secondary",
                            Name = "Dips",
                            VideoUrl = "https://www.youtube.com/results?search_query=How+To+Do+Bench+Dips+%7C+Exercise+Demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 27,
                            ExerciseType = "Accessory",
                            Name = "Lateral Raises",
                            VideoUrl = "https://www.youtube.com/results?search_query=How+to+do+a+lateral+raise+-+20+second+demo",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 28,
                            ExerciseType = "Accessory",
                            Name = "Reverse Tricep Pushups",
                            VideoUrl = "https://www.youtube.com/results?search_query=Reverse+Tricep+Pushups",
                            WorkoutType = "UpperBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 30,
                            ExerciseType = "Core",
                            Name = "Squat",
                            VideoUrl = "https://www.youtube.com/results?search_query=The+Back+Squat",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 31,
                            ExerciseType = "Core",
                            Name = "Deadlift",
                            VideoUrl = "https://www.youtube.com/results?search_query=The+Deadlift%3A+CrossFit+Foundational+Movement",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 33,
                            ExerciseType = "Secondary",
                            Name = "Bulgarian Split Squat",
                            VideoUrl = "https://www.youtube.com/results?search_query=Bulgarian+Split+Squat+Step+by+Step+Guide",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 34,
                            ExerciseType = "Secondary",
                            Name = "Romanian Deadlift",
                            VideoUrl = "https://www.youtube.com/results?search_query=Movement+Demo+-+The+Romanian+Deadlift",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 35,
                            ExerciseType = "Secondary",
                            Name = "Step-Ups",
                            VideoUrl = "https://www.youtube.com/results?search_query=Box+Step+Up+Demo",
                            WorkoutType = "LowerBodyStrength"
                        },
                        new
                        {
                            ExerciseId = 37,
                            ExerciseType = "Secondary",
                            Name = "Glute Ham Raises",
                            VideoUrl = "https://www.youtube.com/results?search_query=glute+ham+raises+demo",
                            WorkoutType = "LowerBodyStrength"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
